# Generated by Django 5.1 on 2024-09-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_token_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='upload_images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
