# Generated by Django 5.1 on 2024-09-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_upload_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='upload_images',
            new_name='upload_promotional_images_1',
        ),
        migrations.AddField(
            model_name='shop',
            name='upload_promotional_images_2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='upload_promotional_images_3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='upload_promotional_images_4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
